### PR TITLE
[FIX][no-unused-vars] add EnumMember

### LINKED ISSUE #235: [no-unused-vars] enum members throw errors
**Repro**

```TS
enum FormFieldIds {
	PHONE = 'phone',
	EMAIL = 'email',
}
interface IFoo {
	fieldName: FormFieldIds,
}
```

**Expected Result**

I expected that code does not cause errors

**Actual Result**

Throw errors:
'PHONE' is assigned a value but never used.
'EMAIL' is assigned a value but never used.

**Additional Info**
You can reproduce behavior on your computed if download repository:
https://github.com/mogafk/reproduce-enum-errors

also i create [pr](https://github.com/bradzacher/eslint-plugin-typescript/pull/236) with fix. But i not sure that it real bug. Sorry if i wrong

**Versions**

"eslint": "^5.10.0",
"eslint-plugin-typescript": "^0.14.0",
"typescript": "^3.1.1",
"typescript-eslint-parser": "^21.0.2",

### PR DESCRIPTION
**Pull request by mogafk**
Fixes #235

### CODE REVIEW

**Comment by j-f1** [comment]
You might want to make sure the email you used to commit is added to your account so you get credit.

**Comment by micaelmbagira** [comment]
@armano2 when do you plan to release this?

**Comment by bradzacher** [comment]
This is part of the upcoming 1.0.0 release, coming soon.
Please see the 1.0.0 issue for discussion.

**Comment by j-f1** [comment]
(#151)

**Pull request merged**
