### PR TITLE
Updated NodeType of TSTypeLiteral to TSLiteralType for typescript 2.9.x

### PR DESCRIPTION
**Pull request by weikinhuang**
After upgrading to `typescript@2.9.2` and `typescript-eslint-parser@16.0.0` I've encountered an issue with running the `typescript/no-type-alias` rule against this file:

```typescript
// Manually declaring because the official does not export classvalue
declare module 'classnames' {
  // Type definitions for classnames 2.2
  // Project: https://github.com/JedWatson/classnames
  // Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
  // TypeScript Version: 2.3
  export type ClassValue = string | number | ClassDictionary | ClassArray | undefined | null | false;

  interface ClassDictionary {
    [id: string]: boolean | undefined | null;
  }

  export interface ClassArray extends Array<ClassValue> { } // eslint-disable-line typescript/no-empty-interface
  type ClassNamesFn = (...classes: ClassValue[]) => string;

  const classNames: ClassNamesFn;

  export default classNames;
}
```

It would crash with:

```
Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at getMessage (/foobar/node_modules/eslint-plugin-typescript/lib/rules/no-type-alias.js:194:26)
    at validateTypeAliases (/foobar/node_modules/eslint-plugin-typescript/lib/rules/no-type-alias.js:280:30)
    at node.types.forEach.type (/foobar/node_modules/eslint-plugin-typescript/lib/rules/no-type-alias.js:296:21)
    at Array.forEach (<anonymous>)
    at validateCompositions (/foobar/node_modules/eslint-plugin-typescript/lib/rules/no-type-alias.js:292:24)
    at validateNode (/foobar/node_modules/eslint-plugin-typescript/lib/rules/no-type-alias.js:310:17)
    at VariableDeclaration (/foobar/node_modules/eslint-plugin-typescript/lib/rules/no-type-alias.js:322:21)
    at listeners.(anonymous function).forEach.listener (/foobar/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/foobar/node_modules/eslint/lib/util/safe-emitter.js:47:38)
```

At which point, I added this changeset, and some logging for the node, I got:

```
{ type: 'TSLiteralType',
  range: [ 388, 393 ],
  loc:
   { start: { line: 7, column: 95 },
     end: { line: 7, column: 100 } },
  transformFlags: undefined,
  literal:
   { type: 'Literal',
     range: [ 388, 393 ],
     loc: { start: [Object], end: [Object] },
     value: false,
     raw: 'false' } }

/foobar/types/classnames.d.ts
  7:96  error  Type aliases are not allowed  typescript/no-type-alias
```

### CODE REVIEW

**Comment by weikinhuang** [comment]
I would appreciate some pointers on how to create a test case for this, as this only affects the newer version of typescript and the parser

**Comment by weikinhuang** [comment]
@JamesHenry Prior to the update,

```typescript
export type ClassValue = string | number | ClassDictionary | ClassArray | undefined | null | false;
```

was not caught by the `typescript/no-type-alias` rule, and should probably continue to not to be. The configuration I'm using is:

```json
        'typescript/no-type-alias': ['error', {
          allowAliases: 'in-unions-and-intersections',
          allowCallbacks: true,
          allowsLiterals: 'in-unions-and-intersections',
          allowMappedTypes: 'in-unions-and-intersections',
        }],
```

**Comment by scottohara** [comment]
I have just upgraded one of my projects to `typescript@2.9.2` + `typescript-eslint-parser@16.0.1`.

I'm getting the same error as @weikinhuang:

```
TypeError: Cannot read property '0' of undefined
   at getMessage (/foobar/node_modules/eslint-plugin-typescript/lib/rules/no-type-alias.js:194:26)
   ...
```

for configuration:

```json
"typescript/no-type-alias": ["error", {
  "allowAliases": "in-unions-and-intersections",
  "allowCallbacks": true,
  "allowsLiterals": "in-unions-and-intersections",
  "allowMappedTypes": "in-unions-and-intersections",
}]
```

and source:

```typescript
export type <SomeType> = <union of types>
```

Looking at this patch, what is unclear (to me) is where upstream the change from `TSTypeLiteral` -> `TSLiteralType` occurred, that causes the error (and the need for this PR)?

My assumption was that it must have been a change in `typescript-eslint-parser`, but in that project I can find no references to `TSLiteralType`.

Has anyone identified yet if the change from `TSTypeLiteral` -> `TSLiteralType` was intentional?

**Comment by xt0rted** [comment]
I just started setting up ESLint for my project and ran into this issue as well.

My package.json has the following versions in it
```json
{
  "devDependencies": {
    "eslint": "5.5.0",
    "eslint-plugin-typescript": "0.12.0",
    "typescript": "3.0.3",
    "typescript-eslint-parser": "18.0.0"
  }
}
```

**Comment by bradzacher** [comment]
Hi @weikinhuang,
Could you please add some tests for your change?

**Comment by armano2** [comment]
`TSLiteralType` is not the same as `TSTypeLiteral`

`TSLiteralType` is a string like type => alias

and this issue got fixed in https://github.com/bradzacher/eslint-plugin-typescript/commit/f6041a6294ff33b7b6364e66475ae440bf6f1c05

**Comment by bradzacher** [comment]
Cool beans, thanks @armano2 
Closing this as fixed.

**Comment by weikinhuang** [comment]
Thanks

**Pull request closed without merging**
