### PR TITLE
chore: update package dependencies (fixes #184)

### LINKED ISSUE #184: Add explicit dependencies
We have a peer dependency on `eslint`, and a direct dependency on `typescript-eslint-parser`.

I've submitted https://github.com/eslint/eslint/issues/11127, maybe it'll be considered.

Regardless, we should at least be explicitly defining our required versions via peer dependencies.

(as per discussion on #183)

### PR DESCRIPTION
**Pull request by weirdpattern**
Updates package dependencies and introduces eslint and typescript-eslint-parser as peer dependencies

Considerations:
1. The PR includes minor lint changes to 3 rules introduced with the newer eslint version
2. The PR bumps all versions to latest except: eslint-plugin-node (peer dependency of eslint-config-eslint), typescript and typescript-eslint-parser (these two being worked in #174)
3. Peer dependencies are kind of loose (at least eslint), we can change that...

### CODE REVIEW

**Comment by weirdpattern** [comment]
@bradzacher alright, this should be ready for one last code review and merge...

By the way, I'm seeing some odd behaviors after #182 was merged... I think the .vscode/settings.json eslint.validate autofix option is in direct conflict with `prettier-eslint` and `eslint-docs`... saving a file gives one format, running `yarn format` gives another, same for the eslint-docs script... this causes a lot of unnecessary LOC changes... 

Good examples of this are: 
- The README.md for eslint-docs 
- The lib/rules/class-name-casing.js rule for prettier-eslint

I should probably create a bug for this... just want you to double check, maybe is something I'm doing wrong?

**Comment by bradzacher** [comment]
hmm. have you got the Prettier extension installed?
I may have been a bit eager chucking those config options in.

**Comment by weirdpattern** [comment]
Unless is not this one... then yes...
extensions

I will review my own settings tomorrow... but as far as I can tell... everything should be in order

**Comment by weirdpattern** [comment]
And I just updated the package.json with the lint-staged change that you just merged

**Comment by weirdpattern** [comment]
I was pretty sure it was something with my configuration... :smile:

**Pull request merged**
