### PR TITLE
Camelcase failing test case

### PR DESCRIPTION
**Pull request by guylil**
Test should pass but doesn't

#goodnessSquad @mightyiam

### CODE REVIEW

**Comment by j-f1** [comment]
Can you run `npm run lint -- --fix` and push the changes? This will fix the lint errors so that Travis can run your tests.

**Comment by mightyiam** [comment]
@j-f1 the prettier failures are unrelated. I suggest they be handled in the form of #93 or #94.

**Comment by JamesHenry** [comment]
Thanks for contributing, @guylil! #94 has now been merged

**Comment by mightyiam** [comment]
This should be re-opened.

**Comment by mightyiam** [comment]
This is still failing. @guylil could you please update the branch by merging master?

**Comment by bradzacher** [comment]
Hi @guylil 

I'm going to close this PR due to unresponsiveness.
I've opened #177 to track this issue so others can pick it up if they like.

Feel free to submit a new PR if you want to get back into it and fix this.

**Pull request closed without merging**
