### PR TITLE
[FEAT] [BREAKING] [no-unused-vars] remove implicit dep on base rule

### PR DESCRIPTION
**Pull request by bradzacher**
Similar to what we've done with both indent, and camelcase.
Rather than forcing users to configure both our rule and the base rule (which has been a source of confusion), this lets users just use our rule.

```diff
 {
-    "no-unused-vars": ["error", { config }],
+    "no-unused-vars": "off",
-    "typescript/no-unused-vars": "error",
+    "typescript/no-unused-vars": ["error", { config }],
 }
```

### CODE REVIEW

**Comment by j-f1** [comment]
I’m wondering if we should be copying ESLint’s docs or just linking to them. I’m in favor of linking to the original docs and describing how our rule is different. This allows us to have the most up-to-date docs for the rule that we’re building on, and makes it easier for folks to see how our rule differs.

**Comment by armano2** [comment]
It's not really good idea to do it for no unused vars, other plugins can modify eslint used property, and there can be code effects when using this with eslint-plugin-vue

**Comment by armano2** [comment]
We shouldn't enable eslint rules anyway..

**Comment by bradzacher** [comment]
@armano2 - this won't break eslint-plugin-vue.
All of the eslint plugins run and interop on the same contexts.
It means that if someone is using `eslint-plugin-vue/no-unused-vars`, then it'll still work fine, they'll just be using our rule as their base one instead of the base eslint rule:

```diff
{
    "no-unused-vars": "off",
    "typescript/no-unused-vars": ["error", { config }],
    "vue/no-unused-vars": "error"
}
```

I think in this case it's fine because we are a language-level plugin.
This gives us the freedom to (if we want) switch to use parser services in future (do the parser services report on unused?), without having to do a breaking version bump.

---

@j-f1 I actually thought the same thing. I copied it because that's what we'd done for the other rules.
I'll raise a separate PR to rewrite all of docs together.

**Comment by armano2** [comment]
fair enough i didn't think about 
```
   --noUnusedLocals                    Report Errors on Unused Locals.
   --noUnusedParameters                Report Errors on Unused Parameters.
```

**Pull request merged**
