### PR TITLE
Migrate typescript-eslint-parser to 21.0.2

### PR DESCRIPTION
**Pull request by armano2**
To make it work this PR has to be merged due to bug in visitor-tree

- [x] ~~https://github.com/eslint/typescript-eslint-parser/pull/554~~
- [x] ~~https://github.com/eslint/typescript-eslint-parser/pull/560~~
- [x] ~~https://github.com/eslint/typescript-eslint-parser/pull/561~~
- [x] ~~https://github.com/eslint/typescript-eslint-parser/pull/562~~
- [x] ~~https://github.com/eslint/typescript-eslint-parser/pull/565~~
- [x] ~~https://github.com/eslint/typescript-eslint-parser/pull/571~~
- [x] ~~New release of [`typescript-eslint-parser`](https://github.com/eslint/typescript-eslint-parser)~~

unblocks #117, #181 PR

fixes: #152, #155, #126, #164, #166, #171, #193, #189, #143, #33

### CODE REVIEW

**Comment by weirdpattern** [comment]
This looks so much cleaner... thank you @armano2 .
Hoping the new version of the parser gets released soon...

**Comment by bradzacher** [comment]
I should go through and read up on the new nodes.
It looks like they've added a lot of really helpful stuff to make dealing with the AST easier!

**Comment by armano2** [comment]
@bradzacher for everyone who wants to try new version i suggest to use [npm/@armano/typescript-eslint-parser](https://www.npmjs.com/package/@armano/typescript-eslint-parser) i published version with my fixes to parser

**Comment by armano2** [comment]
do you want me to add test scenario for #143? it's not really related to this code but to fix in visitor

**Comment by bradzacher** [comment]
so close...!

**Comment by bradzacher** [comment]
awesome! I'll give it one final eyeball now

**Pull request merged**
